"""Protocol constants for Weixin iLink API."""

MESSAGE_TYPE_USER = 1
MESSAGE_TYPE_BOT = 2

MESSAGE_ITEM_TEXT = 1
MESSAGE_ITEM_IMAGE = 2
MESSAGE_ITEM_VOICE = 3
MESSAGE_ITEM_FILE = 4
MESSAGE_ITEM_VIDEO = 5

MESSAGE_STATE_FINISH = 2

SESSION_EXPIRED_ERRCODE = -14

DEFAULT_LONG_POLL_TIMEOUT_MS = 35_000
DEFAULT_API_TIMEOUT_MS = 15_000

MAX_CONSECUTIVE_FAILURES = 3
BACKOFF_DELAY_MS = 30_000
RETRY_DELAY_MS = 2_000
SESSION_PAUSE_MS = 60 * 60 * 1000
TEXT_CHUNK_LIMIT = 4000

MAX_QR_REFRESH_COUNT = 3
QR_STATUS_LONG_POLL_MS = 35_000
DEFAULT_QR_LOGIN_TIMEOUT_S = 480.0
